require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rubocop-discourse: default.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{bundle,rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - test/**/*
    - 'test/controllers/people_controller_test.rb'